engines:
  duplication:
    exclude_paths:
      - 'test/**'
      - 'msvc/llamalog_Test/**'
  metric:
    exclude_paths:
      - 'test/**'
      - 'msvc/llamalog_Test/**'
  coverage:
    exclude_paths:
      - 'test/**'
      - 'msvc/llamalog_Test/**'
exclude_paths:
  - 'lib/**'
