name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    # Setting the path based on the specs saves around 50 seconds during execution
    env:
      Configuration: Debug
      msbuildPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
      #devenvPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE
      vstestconsolePath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
      googletestadapterPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\ked32bft.vu0

    steps:
    - name: Set configuration
      if: ${{ github.ref == 'master' || (github.event_name == 'pull_request' && github.base_ref == 'master') }}
      run: echo "::set-env name=Configuration::Release"

#    - name: Set  MSBuild environment
#      run: |
#      $path = vswhere.exe -latest -property installationPath
#      echo "$path"
#      echo "::set-output name=vspath::$path"

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

     # Caching does not work, MSBuild always performs a full rebuild
#    - name: Cache bin and obj
#      id: cache_Detours
#      uses: actions/cache@v2
#      with:
#        path: |
#          bin
#          obj
#        key: build

    - name: Build solution
      # MSBuild always rebuilds for no known reason, and devenv.com seems painfully slow
      run: . '${{ env.msbuildPath }}\MSBuild.exe' llamalog.sln /p:Configuration=${{ env.Configuration }}
      #run: . '${{ env.devenvPath }}\devenv.com' llamalog.sln /Build "${{ env.Configuration }}|x64"

    - name: Set variables
      if: env.Configuration == 'Debug'
      run: echo "::set-env name=Suffix::d"

    - name: Execute unit tests
      run: . '${{ env.vstestconsolePath }}\VSTest.Console.exe' bin/llamalog_Test_x64$env:Suffix.exe /TestAdapterPath:"${{ env.googletestadapterPath }}"
