name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build  
      uses: mbeckh/build-action@v1
      with:
        projects: llamalog
        tests: llamalog_Test
        codacy-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}
